In [1]:
import pandas as pd

In [4]:
# Lire le CSV
path_file = "../data/risques_majeurs/raw/i119.csv"
df_risques = pd.read_csv(path_file, sep=";", header=2, low_memory=False)

mapping = {
        "Code": "code_insee",
        "Libellé": "nom_commune",
        "risque d'inondations, 2019": "inondations",
        "risque de mouvements de terrain, 2019": "mouvements_terrain",
        "risque de séismes, 2019": "seismes",
        "risque d'avalanches, 2019": "avalanches",
        "risque de feux de forêt, 2019": "feux_foret",
        "risque de lié à des phénomènes atmosphériques, 2019": "phenomenes_atmo",
        "risque d'éruptions volcaniques, 2019": "eruptions",
        "risque industriel, 2019": "industriel",
        "risque nucléaire, 2019": "nucleaire",
        "risque de rupture de barrage, 2019": "barrage",
        "risque lié au transport de marchandises dangereuses, 2019": "transport_matieres",
        "risque lié aux engins de guerre": "engins_guerre",
        "risque d'affaissements miniers, 2019": "affaissements_miniers",
}

df_risques = df_risques.rename(columns=mapping).drop(columns=["nom_commune"])

df_risques["code_insee"] = df_risques["code_insee"].apply(lambda x: str(x).zfill(5))
df_risques

,code_insee,inondations,mouvements_terrain,seismes,avalanches,feux_foret,phenomenes_atmo,eruptions,industriel,nucleaire,barrage,transport_matieres,engins_guerre,affaissements_miniers
0,01001,1,0,2,0,0,0,0,0,0,0,1,0,0
1,01002,0,1,3,0,0,0,0,0,0,0,0,0,0
2,01004,1,1,3,0,0,0,0,0,0,0,0,0,0
3,01005,0,0,2,0,0,0,0,0,0,0,1,0,0
4,01006,0,0,3,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34930,97613,1,1,3,0,1,0,0,0,0,0,0,0,0
34931,97614,1,1,3,0,1,0,0,0,0,0,0,0,0
34932,97615,1,1,3,0,1,0,0,1,0,0,1,0,0
34933,97616,1,1,3,0,1,0,0,0,0,0,0,0,0
34934,97617,1,1,3,0,1,0,0,0,0,1,0,0,0

In [5]:
# Modification des valeurs commençant par "N/A" en Nan
df_risques = df_risques.replace(r"^N/A.*", pd.NA, regex=True)

In [6]:
df_risques

,code_insee,inondations,mouvements_terrain,seismes,avalanches,feux_foret,phenomenes_atmo,eruptions,industriel,nucleaire,barrage,transport_matieres,engins_guerre,affaissements_miniers
0,01001,1,0,2,0,0,0,0,0,0,0,1,0,0
1,01002,0,1,3,0,0,0,0,0,0,0,0,0,0
2,01004,1,1,3,0,0,0,0,0,0,0,0,0,0
3,01005,0,0,2,0,0,0,0,0,0,0,1,0,0
4,01006,0,0,3,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34930,97613,1,1,3,0,1,0,0,0,0,0,0,0,0
34931,97614,1,1,3,0,1,0,0,0,0,0,0,0,0
34932,97615,1,1,3,0,1,0,0,1,0,0,1,0,0
34933,97616,1,1,3,0,1,0,0,0,0,0,0,0,0
34934,97617,1,1,3,0,1,0,0,0,0,1,0,0,0