In [1]:
import duckdb
import pandas as pd
import os

In [5]:
data_rpls = pd.read_csv("../data/raw/resultats_rpls.csv",sep=';')
data_rpls

/tmp/ipykernel_14366/594476243.py:1: DtypeWarning: Columns (1,2,6,7,8,52,55,56,57,59,60,61,62,63,64,67,83,84,85,87,91,92,93,96,97,99,101,102,179,185,186,187,192,194,196,199) have mixed types. Specify dtype option on import or set low_memory=False.
  data_rpls = pd.read_csv("../data/raw/resultats_rpls.csv",sep=';')

,REG,DEP,DEPCOM_ARM,LIBCOM_DEP,LIBCOM,nb_loues,nb_vacants,nb_vides,nb_asso,nb_occup_finan,...,ener_A_new,ener_B_new,ener_C_new,ener_D_new,ener_E_new,ener_F_new,ener_G_new,ener_NR_new,nb_dpe_realise,perc_dpe_realise
0,84,1,1001,L'Abergement-Clémenciat (01),L'Abergement-Clémenciat,31,1.0,0,0,0,...,0,14,0,4,2,4,0,0,32,"100,00"
1,84,1,1004,Ambérieu-en-Bugey (01),Ambérieu-en-Bugey,1 906,96.0,59,1,47,...,27,13,60,0,1,1,0,0,847,"40,16"
2,84,1,1005,Ambérieux-en-Dombes (01),Ambérieux-en-Dombes,107,3.0,2,0,1,...,0,0,0,0,0,0,0,0,81,"71,68"
3,84,1,1007,Ambronay (01),Ambronay,120,3.0,0,0,6,...,0,0,28,2,0,0,0,0,42,"32,56"
4,84,1,1008,Ambutrix (01),Ambutrix,16,1.0,0,0,0,...,0,4,0,0,0,0,0,0,17,"100,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16854,6,976,97611,Mamoudzou (976),Mamoudzou,1 184,98.0,23.0,22.0,135,...,0,0,0,0,0,0,0,0,0,"0,00"
16855,6,976,97614,Ouangani (976),Ouangani,41,22.0,4.0,4.0,6,...,0,0,0,0,0,0,0,0,0,"0,00"
16856,6,976,97615,Pamandzi (976),Pamandzi,34,2.0,2.0,0.0,1,...,0,0,0,0,0,0,0,0,0,"0,00"
16857,6,976,97616,Sada (976),Sada,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,"0,00"
16858,6,976,97617,Tsingoni (976),Tsingoni,147,97.0,5.0,1.0,102,...,0,0,0,0,0,0,0,0,0,"0,00"

In [6]:
df_rpls = data_rpls[['DEPCOM_ARM','nb_ls2023', 'nb_ls2019']]
df_rpls

      DEPCOM_ARM nb_ls2023 nb_ls2019
0           1001        22        22
1           1004     2 084     1 934
2           1005       104        76
3           1007       129       112
4           1008        17        17
...          ...       ...       ...
16854      97611     1 381       207
16855      97614        61         0
16856      97615        39        27
16857      97616         6         0
16858      97617       193         0

[16859 rows x 3 columns]

In [7]:
df_rpls.rename(columns={'DEPCOM_ARM': 'code_insee', 'nb_ls2023': 'ls_2023', 'nb_ls2019': 'ls_2019'}, inplace=True)

/tmp/ipykernel_14366/3196580845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rpls.rename(columns={'DEPCOM_ARM': 'code_insee', 'nb_ls2023': 'ls_2023', 'nb_ls2019': 'ls_2019'}, inplace=True)

In [8]:
df_rpls['code_insee'] = df_rpls['code_insee'].replace(' ','').apply(lambda x: str(x).zfill(5))
df_rpls['ls_2023'] = df_rpls['ls_2023'].str.replace('\xa0','').astype(int)
df_rpls['ls_2019'] = df_rpls['ls_2019'].str.replace('\xa0','').astype(int)
df_rpls

/tmp/ipykernel_14366/2532971437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rpls['code_insee'] = df_rpls['code_insee'].replace(' ','').apply(lambda x: str(x).zfill(5))
/tmp/ipykernel_14366/2532971437.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rpls['ls_2023'] = df_rpls['ls_2023'].str.replace('\xa0','').astype(int)
/tmp/ipykernel_14366/2532971437.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rpls['ls_2019'] = df_rpls['ls_2019'].str.replace('\xa0','').astype(int)

      code_insee  ls_2023  ls_2019
0          01001       22       22
1          01004     2084     1934
2          01005      104       76
3          01007      129      112
4          01008       17       17
...          ...      ...      ...
16854      97611     1381      207
16855      97614       61        0
16856      97615       39       27
16857      97616        6        0
16858      97617      193        0

[16859 rows x 3 columns]

In [9]:
df_epci = pd.read_csv("../data/processed/epci_membres.csv",sep=',')
df_epci

,code_insee,nom,pop_tot_commune,pop_mun_commune,siren,epci_nom,epci_type,epci_modeFinancement,total_pop_tot,total_pop_mun,superficie_hectare,superficie_km2,dept_com,bassin_vie,dept_epci
0,01304,Pont-d'Ain,2912,2862,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1122.0,11.0,01,01304,01
1,01199,Jujurieux,2246,2209,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1548.0,15.0,01,01004,01
2,01363,Saint-Jean-le-Vieux,1873,1799,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1517.0,15.0,01,01004,01
3,01314,Priay,1826,1803,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1571.0,16.0,01,01004,01
4,01273,Neuville-sur-Ain,1823,1798,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1991.0,20.0,01,01004,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34996,97601,Acoua,5384,5192,200060465,CA du Grand Nord de Mayotte,CA,FPU,60372,59042,1290.0,13.0,97,97611,976
34997,97603,Bandrele,10529,10282,200060473,CC du Sud,CC,FPU,31945,30898,3514.0,35.0,97,97611,976
34998,97606,Chirongui,9197,8920,200060473,CC du Sud,CC,FPU,31945,30898,2590.0,26.0,97,97611,976
34999,97604,Bouéni,6503,6189,200060473,CC du Sud,CC,FPU,31945,30898,1381.0,14.0,97,97611,976
35000,97609,Kani-Kéli,5716,5507,200060473,CC du Sud,CC,FPU,31945,30898,2004.0,20.0,97,97611,976

In [10]:
df_rpls['diff_percent'] = (((df_rpls['ls_2023'] - df_rpls['ls_2019']) / df_rpls['ls_2019']) * 100).round(2)
df_rpls

/tmp/ipykernel_14366/2044885960.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rpls['diff_percent'] = (((df_rpls['ls_2023'] - df_rpls['ls_2019']) / df_rpls['ls_2019']) * 100).round(2)

      code_insee  ls_2023  ls_2019  diff_percent
0          01001       22       22          0.00
1          01004     2084     1934          7.76
2          01005      104       76         36.84
3          01007      129      112         15.18
4          01008       17       17          0.00
...          ...      ...      ...           ...
16854      97611     1381      207        567.15
16855      97614       61        0           inf
16856      97615       39       27         44.44
16857      97616        6        0           inf
16858      97617      193        0           inf

[16859 rows x 4 columns]

In [11]:
df_rpls['code_insee'] = df_rpls['code_insee'].apply(lambda x: "75056" if x.startswith("75") else x)
df_rpls

/tmp/ipykernel_14366/806156749.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rpls['code_insee'] = df_rpls['code_insee'].apply(lambda x: "75056" if x.startswith("75") else x)

      code_insee  ls_2023  ls_2019  diff_percent
0          01001       22       22          0.00
1          01004     2084     1934          7.76
2          01005      104       76         36.84
3          01007      129      112         15.18
4          01008       17       17          0.00
...          ...      ...      ...           ...
16854      97611     1381      207        567.15
16855      97614       61        0           inf
16856      97615       39       27         44.44
16857      97616        6        0           inf
16858      97617      193        0           inf

[16859 rows x 4 columns]

In [12]:
df_rpls[df_rpls['code_insee'].str.startswith('75')]

      code_insee  ls_2023  ls_2019  diff_percent
13970      75056     1140     1000         14.00
13971      75056      700      676          3.55
13972      75056     1598     1497          6.75
13973      75056     2447     2286          7.04
13974      75056     3094     2786         11.06
13975      75056      715      651          9.83
13976      75056      391      386          1.30
13977      75056      716      581         23.24
13978      75056     2210     2002         10.39
13979      75056     7318     6846          6.89
13980      75056    10631    10155          4.69
13981      75056    18077    16800          7.60
13982      75056    35111    33988          3.30
13983      75056    19624    19047          3.03
13984      75056    23532    22492          4.62
13985      75056     5514     5366          2.76
13986      75056    15223    14662          3.83
13987      75056    23413    21421          9.30
13988      75056    35622    34379          3.62
13989      75056    36023    34451          4.56

In [13]:
query = """
SELECT 
df_epci.dept_epci as dept_id,
df_epci.siren as epci_id,
df_epci.epci_nom AS epci_lib,
'i037' as id_indicator,
case WHEN sum(df_rpls.ls_2019) = 0 THEN null
     ELSE ROUND((sum(df_rpls.ls_2023) - sum(df_rpls.ls_2019)) / sum(df_rpls.ls_2019)  * 100, 2) END as valeur_brute,
'2023' as annee
FROM df_epci
JOIN df_rpls 
    ON df_epci.code_insee = df_rpls.code_insee
GROUP BY df_epci.dept_epci,df_epci.siren, df_epci.epci_nom
ORDER BY df_epci.dept_epci,df_epci.siren
"""

df_final = duckdb.query(query)

In [14]:
df_final

┌─────────┬───────────┬────────────────────────────────────────────────────────────┬──────────────┬──────────────┬─────────┐
│ dept_id │  epci_id  │                          epci_lib                          │ id_indicator │ valeur_brute │  annee  │
│ varchar │   int64   │                          varchar                           │   varchar    │    double    │ varchar │
├─────────┼───────────┼────────────────────────────────────────────────────────────┼──────────────┼──────────────┼─────────┤
│ 01      │ 200029999 │ CC Rives de l'Ain - Pays du Cerdon                         │ i037         │        11.54 │ 2023    │
│ 01      │ 200040350 │ CC Bugey Sud                                               │ i037         │         1.26 │ 2023    │
│ 01      │ 200042497 │ CC Dombes Saône Vallée                                     │ i037         │        13.89 │ 2023    │
│ 01      │ 200042935 │ CA Haut-Bugey Agglomération                                │ i037         │         1.06 │ 2023    │
│ 01      │ 200069193 │ CC de la Dombes                                            │ i037         │         8.97 │ 2023    │
│ 01      │ 200070118 │ CC Val de Saône Centre                                     │ i037         │        11.77 │ 2023    │
│ 01      │ 200070555 │ CC de la Veyle                                             │ i037         │        10.35 │ 2023    │
│ 01      │ 200071371 │ CC Bresse et Saône                                         │ i037         │         3.14 │ 2023    │
│ 01      │ 200071751 │ CA du Bassin de Bourg-en-Bresse                            │ i037         │         1.75 │ 2023    │
│ 01      │ 240100610 │ CC de la Côtière à Montluel                                │ i037         │         8.41 │ 2023    │
│ ·       │     ·     │              ·                                             │  ·           │           ·  │  ·      │
│ ·       │     ·     │              ·                                             │  ·           │           ·  │  ·      │
│ ·       │     ·     │              ·                                             │  ·           │           ·  │  ·      │
│ 974     │ 249740077 │ CA CIVIS (Communauté Intercommunale des Villes Solidaires) │ i037         │         9.67 │ 2023    │
│ 974     │ 249740085 │ CA du Sud                                                  │ i037         │        18.17 │ 2023    │
│ 974     │ 249740093 │ CA Intercommunale de la Réunion Est (CIREST)               │ i037         │         4.77 │ 2023    │
│ 974     │ 249740101 │ CA Territoire de la Côte Ouest (TCO)                       │ i037         │         8.23 │ 2023    │
│ 974     │ 249740119 │ CA Intercommunale du Nord de la Réunion (CINOR)            │ i037         │         7.09 │ 2023    │
│ 976     │ 200050532 │ CC de Petite-Terre                                         │ i037         │        694.0 │ 2023    │
│ 976     │ 200059871 │ CC du Centre-Ouest                                         │ i037         │         NULL │ 2023    │
│ 976     │ 200060457 │ CA de Dembeni / Mamoudzou                                  │ i037         │       598.55 │ 2023    │
│ 976     │ 200060465 │ CA du Grand Nord de Mayotte                                │ i037         │      2177.78 │ 2023    │
│ 976     │ 200060473 │ CC du Sud                                                  │ i037         │         NULL │ 2023    │
├─────────┴───────────┴────────────────────────────────────────────────────────────┴──────────────┴──────────────┴─────────┤
│ 1267 rows (20 shown)                                                                                           6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [15]:
df_final.write_csv("../data/processed/i037_rpls_epci.csv")

In [ ]:
duckdb.query("SELECT COUNT(DISTINCT siren) FROM df_epci;")

┌───────────────────────┐
│ count(DISTINCT siren) │
│         int64         │
├───────────────────────┤
│                  1267 │
└───────────────────────┘

In [ ]:
duckdb.query("""SELECT COUNT(DISTINCT df_epci.siren)
FROM df_epci
JOIN df_rpls ON df_epci.code_insee = df_rpls.code_insee;""")

┌───────────────────────────────┐
│ count(DISTINCT df_epci.siren) │
│             int64             │
├───────────────────────────────┤
│                          1266 │
└───────────────────────────────┘